var car = "honda";
console.log("Is car a 'honda'? I predict that it is.");
console.log(car == "honda", "\n");
car = "mehran";
console.log("Is car a 'mehran'? I predict that it is.");
console.log(car == "mehran", "\n");
car = "ferrari";
console.log("Is car a 'ferrari'? I predict that it is.");
console.log(car == "ferrari", "\n");
car = "supra";
console.log("Is car a 'supra'? I predict that it is.");
console.log(car == "supra", "\n");
car = "toyota";
console.log("Is car a 'honda'? I predict that it is.");
console.log(car == "honda");
console.log("It is " + car + ".\n");
car = "rolls royce";
console.log("Is car a 'mehran'? I predict that it is.");
console.log(car == "mehran");
console.log("It is " + car + ".\n");
car = "toyota";
console.log("Is car a 'corolla'? I predict that it is.");
console.log(car == "corlla");
console.log("It is " + car + ".\n");
car = "audi";
console.log("Is car a 'suzuki'? I predict that it is.");
console.log(car == "suzuki");
console.log("It is " + car + ".\n");
// Done.
